#!/bin/bash

token=$(jq -r .slackToken test/data/environment.json)
channel=$(jq -r .slackChannel test/data/environment.json)

echo "Token: ${token}"

r1=$(curl \
    --silent \
    --header "authorization: Bearer ${token}" \
    --header "content-type: application/json; charset=utf-8" \
    --header "content-size: 243" \
    --data   '{"channel":"'${channel}'","blocks":[{"type":"rich_text","elements":[{"type":"rich_text_preformatted","elements":[{"type":"text","text":"Rich Text PreFormatted Test","style":{"bold":true,"italic":true,"strike":true,"code":true}}],"border":1}]}]}' \
    --request POST \
    https://slack.com/api/chat.postMessage)

echo "Post: ${r1}"

ts=$(echo ${r1} | jq -r .message.ts)
message='{"channel":"'${channel}'","message_ts":'${ts}'}'
size=$(echo -n ${message} | wc -c)

echo "${message} => S: ${size}"

r2=$(curl \
    --silent \
    --header "authorization: Bearer ${token}" \
    --header "content-type: application/json; charset=utf-8" \
    --request GET \
    "https://slack.com/api/chat.getPermalink?channel=${channel}&message_ts=${ts}")

echo "Reply: ${r2}"




#curl \
#    --header "authorization: Bearer ${token}" \
#    --header "content-type: application/json; charset=utf-8" \
#    --request GET \
#    https://slack.com/api/auth.test
#echo
#echo

#curl \
#    --header "authorization: Bearer ${token}" \
#    --header "content-type: application/json; charset=utf-8" \
#    --header "content-size: 243" \
#    --data   '{"channel":"'${channel}'","blocks":[{"type":"rich_text","elements":[{"type":"rich_text_preformatted","elements":[{"type":"text","text":"Rich Text PreFormatted Test","style":{"bold":true,"italic":true,"strike":true,"code":true}}],"border":1}]}]}' \
#    --request POST \
#    https://slack.com/api/chat.postMessage
#echo
#echo

#curl \
#    --header "authorization: Bearer ${token}" \
#    --header "content-type: application/json; charset=utf-8" \
#    --header "content-size: 225" \
#    --data   '{"channel":"'${channel}'","blocks":[{"type":"rich_text","elements":[{"type":"rich_text_preformatted","elements":[{"type":"text","text":"Rich Text PreFormatted Test","style":{"bold":true,"italic":true,"strike":true,"code":true}}]}]}]}' \
#    --request POST \
#    https://slack.com/api/chat.postMessage
#
#echo
#echo
#curl \
#    --header "authorization: Bearer ${token}" \
#    --header "content-type: application/json; charset=utf-8" \
#    --header "content-size: 236" \
#    --data   '{"channel":"'${channel}'","blocks":[{"type":"rich_text","elements":[{"type":"rich_text_quote","elements":[{"type":"text","text":"Rich Text PreFormatted Test","style":{"bold":true,"italic":true,"strike":true,"code":true}}],"border":1}]}]}' \
#    --request POST \
#    https://slack.com/api/chat.postMessage
#
#echo
#echo
#curl \
#    --header "authorization: Bearer ${token}" \
#    --header "content-type: application/json; charset=utf-8" \
#    --header "content-size: 225" \
#    --data   '{"channel":"'${channel}'","blocks":[{"type":"rich_text","elements":[{"type":"rich_text_quote","elements":[{"type":"text","text":"Rich Text PreFormatted Test","style":{"bold":true,"italic":true,"strike":true,"code":true}}]}]}]}' \
#    --request POST \
#    https://slack.com/api/chat.postMessage
#
#echo
#echo


